### ISSUE TITLE
AudioStrobe Compatibility

### ISSUE THREAD

**Issue by heyakyra** [adolfintel/sine#2]
If this isn't already a feature

**Comment by adolfintel** [comment]
As I said in the other issue, the application is currently not being developed. Besides that, AudioStrobe seems to be a proprietary technology (correct me if I'm wrong)

**Comment by heyakyra** [comment]
I see, I thought maybe it could be reverse engineered as many free software projects do for comatability with proprietary formats. Not sure what the patent situation is, though
