### ISSUE TITLE
Sound Modulation (Embedding Entrainment)

### ISSUE THREAD

**Issue by heyakyra** [adolfintel/sine#3]
Allow for turning other audio (songs, etc.) into entrainment

**Comment by adolfintel** [comment]
At the moment the application is no longer being developed (bug fixes only), but I am looking forward to do a complete overhaul of this application and this is one of the features that I plan to introduce.

**Comment by heyakyra** [comment]
A complete overhaul sounds exciting! Have you already made some first steps, or do you know what technologies you would be using for it?

**Comment by adolfintel** [comment]
This is the current state of SINE (last update: beginning of october 2018):
* PC version: all platforms received a small update to keep compatibility with newer systems (macos was completely broken) and bug fixes
* Android version: updated to fix all known bugs and for compatibility with Android 8 and newer
* Webapp: no update was necessary
* Currently I'm looking for an iOS developer to port the app.

If I could do a full overhaul of SINE, I'd unify the codebases and do it with javascript (electron for PC, whatever I can come up with for android). Right now there are basically 3 separate versions of SINE that I have to maintain (PC Win/Mac/Linux, Android, Webapp) so making changes and adding features is very time consuming.
Frankly the app isn't popular enough to justify the investment of redoing the whole thing at the moment, but maybe in the next years I might do it anyway.
